# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQwe():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_qwe(self):
    self.driver.get("http://192.168.1.150/loginTest")
    self.driver.set_window_size(1581, 1010)
    self.driver.find_element(By.ID, "el-id-2373-2").click()
    self.driver.find_element(By.ID, "el-id-2373-2").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__wrapper").click()
    self.driver.find_element(By.ID, "el-id-2373-3").click()
    self.driver.find_element(By.ID, "el-id-2373-3").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .el-menu-item > .el-icon").click()
    self.driver.find_element(By.ID, "tab-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".event span").click()
    self.driver.find_element(By.ID, "el-id-2373-130").click()
    self.driver.find_element(By.ID, "el-id-2373-130").send_keys("tesss")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(2)").click()
  
