# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    driver = webdriver.Chrome()
    driver.maximize_window()
  
  def test_untitled(self):
    driver.get("http://192.168.1.185/loginTest")
    #self.driver.set_window_size(1160, 1020)

    self.driver.find_element(By.XPATH, '//*[@id="el-id-1196-2"]').click()
    self.driver.find_element(By.XPATH, '//*[@id="el-id-1196-2"]').send_keys("admin")
    self.driver.find_element(By.XPATH, '//*[@id="el-id-1196-3"]').click()
    self.driver.find_element(By.XPATH, '//*[@id="el-id-1196-3"]').send_keys("admin")
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(3) > span").click()

  
